template = "bach"
strategy-matrix-exclude = "os: ubuntu-latest, julia-arch: x86, julia-version: 1.0.5; os: ubuntu-latest, julia-arch: x86, julia-version: 1.1.1; os: ubuntu-latest, julia-arch: x86, julia-version: 1.2.0;"
