## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

addons:
  apt:
    packages:
    - liblzma-dev
    - xvfb
    - xauth
    - libgtk-3-0
before_script:
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
script:
  - julia -e 'ENV["PYTHON"]=""; Pkg.clone(pwd()); Pkg.build("Queryverse")'
  - $TESTCMD -e 'Pkg.test("Queryverse"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Queryverse")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
