## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

addons:
  apt:
    packages:
    - liblzma-dev
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

script:
  - julia -e 'ENV["PYTHON"]=""; Pkg.clone(pwd()); Pkg.build("Dataverse"); Pkg.test("Dataverse"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Dataverse")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
